name: Python application

on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2
    - name: setup-python
      uses: actions/setup-python@v2
    - name: Install dependencise
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistic
    - name: Lint with isort
      run: |
        pip install isort
        isort .
    - name: pylinter
      uses: alexanderdamiani/pylinter@v1.2.0
      with:
        python-root: '.'
        flake8-flags: '--count --show-source --statistics'
        mypy-flags: '--ignore-missing-imports'
        fail-on-isort: true
